server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.89.163:1521:ORCLCDB
    username: c##sherry
    password: Conan_Sherry#4869

#   HikariCP
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      login-timeout: 30
#      connection-timeout: 50000
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: Hikari-Pool
#      max-lifetime: 1800000
#      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        # 数据库方言
        dialect: org.hibernate.dialect.Oracle12cDialect

logging:
  level:
    root: debug
  file:
    path: logs/
